"""
Deployment approval report generator.

Takes a list of GateResult objects and produces a structured markdown report
with decision, gate details, and conservation status.
"""

from __future__ import annotations

from typing import Sequence

try:
    from .gate import GateResult, ConservationTracker
except ImportError:
    from gate import GateResult, ConservationTracker


_SEVERITY_ICON = {
    "critical": "🔴",
    "error": "🟠",
    "warning": "🟡",
    "info": "🔵",
}


def _decision_icon(decision: str) -> str:
    return {"APPROVED": "✅", "BLOCKED": "🚫", "WARNED": "⚠️"}.get(decision, "💬")


def _gate_icon(result: GateResult) -> str:
    if result.passed:
        return "✅"
    return _SEVERITY_ICON.get(result.severity, "❓")


def generate_report(
    results: Sequence[GateResult],
    *,
    decision: str = "COMMENT",
    blocking_failures: Sequence[GateResult] | None = None,
    repo: str = "",
    pr_number: int | None = None,
    author: str = "",
    conservation: ConservationTracker | None = None,
) -> str:
    """Generate a full markdown deployment approval report.

    Args:
        results: List of GateResult from run_all_gates().
        decision: Deployment decision (APPROVED/BLOCKED/WARNED).
        blocking_failures: Gates that blocked deployment (if any).
        repo: Repository name for header.
        pr_number: PR number for header.
        author: PR author for header.
        conservation: Conservation tracker for deployment rate info.

    Returns:
        Markdown-formatted report string.
    """
    total = len(results)
    passed = sum(1 for r in results if r.passed)
    failed = total - passed

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────
    lines.append("## 🚦 PLATO Deployment Approval Report\n")

    if repo or pr_number:
        header_parts = []
        if repo:
            header_parts.append(f"**Repo:** `{repo}`")
        if pr_number:
            header_parts.append(f"**PR:** #{pr_number}")
        if author:
            header_parts.append(f"**Author:** @{author}")
        lines.append(" | ".join(header_parts))
        lines.append("")

    # ── Decision ─────────────────────────────────────────────
    icon = _decision_icon(decision)
    lines.append(f"### {icon} Decision: **{decision}**\n")

    if decision == "BLOCKED" and blocking_failures:
        lines.append("Deployment is **blocked** by the following gates:\n")
        for r in blocking_failures:
            lines.append(f"- 🔴 **{r.name}**: {r.message}")
        lines.append("")

    # ── Summary ─────────────────────────────────────────────
    lines.append("### Summary\n")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Gates Run | {total} |")
    lines.append(f"| Passed | {passed} ✅ |")
    lines.append(f"| Failed | {failed} ❌ |")
    lines.append(f"| Decision | {icon} **{decision}** |")
    lines.append("")

    # ── Conservation status ──────────────────────────────────
    if conservation:
        remaining = conservation.remaining()
        used = conservation.count_today()
        max_daily = conservation.max_per_day
        lines.append("### 🔋 Conservation Status\n")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Daily Limit | {max_daily} deployments/day |")
        lines.append(f"| Used Today | {used} |")
        lines.append(f"| Remaining | {remaining} |")
        lines.append("")

    # ── Detailed Results ─────────────────────────────────────
    lines.append("### Gate Details\n")

    for r in results:
        icon = _gate_icon(r)
        lines.append(f"#### {icon} {r.name}")
        lines.append(f"\n- **Gate ID:** `{r.gate_id}`")
        lines.append(f"- **Status:** {'PASSED' if r.passed else 'FAILED'}")
        lines.append(f"- **Severity:** `{r.severity}`")
        lines.append(f"- **Blocking:** {'Yes' if r.blocking else 'No'}")
        lines.append(f"- **Message:** {r.message}")
        lines.append("")

    # ── Footer ──────────────────────────────────────────────
    lines.append("---")
    lines.append(
        "_Generated by [PLATO Deployment Approval Room]"
        "(https://github.com/SuperInstance/plato-room-deployment-approval)_"
    )

    return "\n".join(lines)


def generate_short_summary(
    results: Sequence[GateResult],
    decision: str = "COMMENT",
) -> str:
    """Generate a one-line summary suitable for status checks.

    Example: "PLATO Deployment: 5/7 gates passed — BLOCKED"
    """
    total = len(results)
    passed = sum(1 for r in results if r.passed)
    return f"PLATO Deployment: {passed}/{total} gates passed — {decision}"
